databases:
  - name: voting-db
    plan: free
    region: oregon
    databaseName: voting
    user: voting_user

services:
  - type: web
    name: voting-backend
    env: node
    region: oregon
    plan: free
    preDeployCommand: cd backend && npm run db:migrate:deploy
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_QxjpUA6oby2d@ep-empty-boat-ahv3ib6x-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require&schema=public"
      - key: REDIS_URL
        value: "https://tolerant-honeybee-35002.upstash.io"
      - key: UPSTASH_REDIS_REST_TOKEN
        value: "AYi6AAIncDI1YzYwMjZmZTQ2OWI0MGE5YTUzYzYxYTk2NmNmMWIxYXAyMzUwMDI"
